# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20160713_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
