# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20180923_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True, verbose_name=b'date of answer')),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, verbose_name=b'Gender'),
        ),
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Person'),
        ),
    ]
