# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20181027_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEventRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(verbose_name='Erstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der Heirat oder der Scheidung'),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ehemann', to='data.Person'),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='status',
            field=models.CharField(choices=[(b'M', 'Heirat'), (b'D', 'Scheidung'), (b'P', 'Partnerschaft'), (b'A', 'Adoption')], max_length=1),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ehefrau', to='data.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sterbbedatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(b'M', 'M\xe4nnlich'), (b'F', 'Weiblich')], max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der Antwort'),
        ),
        migrations.AddField(
            model_name='personeventrelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Person'),
        ),
    ]
