# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20181111_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='familystatusrelation',
            name='ended',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='status',
            field=models.CharField(choices=[(b'M', 'Heirat'), (b'P', 'Partnerschaft'), (b'A', 'Adoption')], max_length=1),
        ),
    ]
