# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20181121_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
