# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAncestryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Ancestry')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Document')),
            ],
        ),
    ]
