# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20181218_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date_unclear',
            field=models.BooleanField(default=False),
        ),
    ]
