# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_person_birth_date_unclear'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'T', 'Baptism'), (b'B', 'Funeral')], max_length=1)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum der Heirat oder der Scheidung')),
                ('date_only_year', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Location')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Person')),
            ],
        ),
    ]
