# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_personevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='children_extern',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
