# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-30 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ancestries'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='media/maps'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/distributions'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='familystatusrelation',
            name='status',
            field=models.CharField(choices=[('M', 'Heirat'), ('P', 'Partnerschaft'), ('A', 'Adoption')], max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/locations'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_extern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/persons'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_extern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich')], max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='person',
            name='siblings_extern',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='type',
            field=models.CharField(choices=[('T', 'Taufe'), ('B', 'Beerdigung'), ('C', 'Konfirmation')], max_length=1),
        ),
    ]
