# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20210108_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrelation',
            options={'ordering': ('document__date',)},
        ),
        migrations.RemoveField(
            model_name='ancestryrelation',
            name='featured',
        ),
        migrations.AddField(
            model_name='ancestry',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Person'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='type',
            field=models.CharField(choices=[('T', 'Taufe'), ('B', 'Beerdigung'), ('C', 'Konfirmation'), ('S', 'Settlement')], max_length=1),
        ),
    ]
