# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20210124_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncestryTreeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Ancestry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Person')),
            ],
        ),
    ]
